
import React from 'react';
import AntdStyleRegistry from "../components/antd-style-registry";

import LayoutHeader from '@/app/_layout/LayoutHeader';
import LayoutMain from '@/app/_layout/LayoutMain';

import './globals.scss';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link href='https://fonts.googleapis.com/css2?family=Inter&display=optional' rel="stylesheet" /> */}
        <style>
          {/* {extraStyle} */}
        </style>
      </head>
      <body>
        <AntdStyleRegistry>
          <div>
            <LayoutHeader />
            <LayoutMain>
              {children}
            </LayoutMain>
          </div>
        </AntdStyleRegistry>
      </body>
    </html>
  );
}
